services:
  auth-pg:
    image: postgres
    restart: always
    shm_size: 128mb
    ports: 
      - 5433:5432
    environment:
      POSTGRES_USER: seiji
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: auth
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    networks:
      - portfolio-net

  auth-service:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - 3001:3001
    depends_on:
      auth-pg:
        condition: service_healthy
    networks:
      - portfolio-net

  dev-auth-service:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../.env
    ports:
      - 3001:3001
    depends_on:
      - auth-pg
    volumes:
      - ../src:/app/src
    networks:
      - portfolio-net

networks:
  portfolio-net:
    external: true
